// Bundles bgutils-js into a browser IIFE (global `BGUtils`) and emits it as a
// TypeScript string module (src/lib/bgutilsSource.ts) so it can be injected
// into the PoToken WebView at runtime. Run: `node scripts/build-bgutils.mjs`.
import { build } from 'esbuild';
import { writeFileSync } from 'fs';

const result = await build({
  entryPoints: ['scripts/bgutils-entry.js'],
  bundle: true,
  format: 'iife',
  // Produces `var BGUtils = (() => { ... })()`. The boot script assigns this to
  // `window.BGUtils` from the same closure scope (react-native-webview runs
  // injected JS inside a closure, so a bare top-level `var` isn't global).
  globalName: 'BGUtils',
  platform: 'browser',
  target: ['es2019'],
  write: false,
  minify: true,
});

const code = result.outputFiles[0].text;
const out =
  '// AUTO-GENERATED by scripts/build-bgutils.mjs — do not edit by hand.\n' +
  '// Browser IIFE bundle of bgutils-js, injected into the PoToken WebView.\n' +
  `export const BGUTILS_SOURCE = ${JSON.stringify(code)};\n`;

writeFileSync('src/lib/bgutilsSource.ts', out);
console.log(`wrote src/lib/bgutilsSource.ts (${code.length} bytes)`);
